-- =====================================================================
-- UrTax schema — revision 2 target
-- Source of truth: Data Models/Final-Data-Model.md (revision 2)
-- Diagram:         Data Models/schema-map.html
--
-- This file describes the TARGET schema from revision 2, not the
-- database as it is today. The live database is still built by the
-- SQLAlchemy models in app/models/ plus the Alembic migrations. Use this
-- file to review the design, or to stand up the schema on another
-- database engine.
--
-- Portability rules used throughout:
--   * Plain types only: VARCHAR, INTEGER, BOOLEAN, DATE, TIMESTAMP,
--     DECIMAL, TEXT. No engine-specific types or auto-increment.
--   * Primary keys are VARCHAR(36) UUIDs generated by the app, as the
--     current models do. Every record shown in the UI also has its own
--     unique readable number (CLI-00000001, FLI_0000001, DOC-0000001, ...),
--     handed out from the id_sequences counters (section 0), never by
--     counting rows. URLs and foreign keys keep using the UUID. Lookup tables use INTEGER ids set explicitly in
--     the seed data at the end of this file.
--   * JSON columns are stored as TEXT. Swap to JSONB (PostgreSQL) or JSON
--     (MySQL 5.7+) if you want database-side JSON queries.
--   * Timestamps are stored in UTC. The app writes timezone-aware values.
--   * Value lists (status, filing_method, ...) use CHECK constraints, not
--     ENUM types.
--
-- Engine notes:
--   PostgreSQL : runs as-is. Optionally TIMESTAMP -> TIMESTAMPTZ,
--                TEXT JSON columns -> JSONB.
--   MySQL 8    : runs as-is (InnoDB). CHECK constraints are enforced from 8.0.16.
--                Consider TIMESTAMP -> DATETIME (TIMESTAMP stops at 2038).
--                TEXT columns carry no DEFAULT because MySQL rejects one.
--   SQLite     : runs as-is. Run PRAGMA foreign_keys = ON; per connection.
--   SQL Server : BOOLEAN -> BIT, TEXT -> NVARCHAR(MAX), TIMESTAMP ->
--                DATETIME2. SQL Server rejects multiple cascade paths, so
--                change some ON DELETE CASCADE to NO ACTION if it errors.
--   Oracle     : BOOLEAN -> NUMBER(1) (before 23c), TEXT -> CLOB,
--                VARCHAR -> VARCHAR2.
-- =====================================================================


-- =====================================================================
-- 0. READABLE NUMBER COUNTERS
-- One row per kind of readable number. The app increments current_value
-- with a single UPDATE and formats prefix + zero-padded value, so a
-- number is never reused, even after the record is deleted.
-- =====================================================================

CREATE TABLE id_sequences (
    name        VARCHAR(40)  NOT NULL PRIMARY KEY,     -- CLIENT, CASE, DOCUMENT, ACCOUNT_STAFF, ...
    prefix      VARCHAR(10)  NOT NULL,                 -- CLI-, FLI_, DOC-, ...
    width       INTEGER      NOT NULL,                 -- zero-padded digits
    current_value  INTEGER      NOT NULL DEFAULT 0,
    updated_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);


-- =====================================================================
-- 1. LOOKUP TABLES
-- Adding a role, document type, tax year, tax type, stage or account
-- kind is a single INSERT. Code compares on `code`, never on id or name.
-- Rows are retired with is_active = FALSE, never deleted.
-- =====================================================================

CREATE TABLE account_types (
    id               INTEGER      NOT NULL PRIMARY KEY,
    code             VARCHAR(30)  NOT NULL UNIQUE,      -- CLIENT, STAFF, ADMIN, HR
    name             VARCHAR(80)  NOT NULL,
    description      VARCHAR(255),
    number_prefix    VARCHAR(10)  NOT NULL UNIQUE,      -- CLT, STF, ADM, HR
    portal_path      VARCHAR(80)  NOT NULL,             -- /client, /staff, ...
    has_case_access  BOOLEAN      NOT NULL DEFAULT FALSE,
    is_internal      BOOLEAN      NOT NULL DEFAULT FALSE,   -- firm side (STAFF, ADMIN, HR); may use internal chat
    sort_order       INTEGER      NOT NULL DEFAULT 0,
    is_active        BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE staff_roles (
    id               INTEGER      NOT NULL PRIMARY KEY,
    code             VARCHAR(30)  NOT NULL UNIQUE,      -- INITIATOR, PREPARER, REVIEWER, MANAGER
    name             VARCHAR(80)  NOT NULL,
    description      VARCHAR(255),
    is_case_role     BOOLEAN      NOT NULL DEFAULT TRUE, -- can be assigned on a case
    sort_order       INTEGER      NOT NULL DEFAULT 0,
    is_active        BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE tax_years (
    id               INTEGER      NOT NULL PRIMARY KEY,
    year             INTEGER      NOT NULL UNIQUE,
    name             VARCHAR(80)  NOT NULL,             -- e.g. "Tax year 2025"
    description      VARCHAR(255),
    is_open          BOOLEAN      NOT NULL DEFAULT TRUE, -- shown in the year picker
    is_default       BOOLEAN      NOT NULL DEFAULT FALSE,
    filing_deadline  DATE,
    sort_order       INTEGER      NOT NULL DEFAULT 0,
    is_active        BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE tax_types (
    id               INTEGER      NOT NULL PRIMARY KEY,
    code             VARCHAR(50)  NOT NULL UNIQUE,      -- individual, business, ... (= tax_filings.filing_type)
    name             VARCHAR(80)  NOT NULL,
    description      VARCHAR(255),
    sort_order       INTEGER      NOT NULL DEFAULT 0,
    is_active        BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE document_categories (
    id               INTEGER      NOT NULL PRIMARY KEY,
    code             VARCHAR(50)  NOT NULL UNIQUE,      -- Personal, Income, Foreign_Information, ...
    name             VARCHAR(80)  NOT NULL,             -- label shown on the documents pages
    description      VARCHAR(255),
    sort_order       INTEGER      NOT NULL DEFAULT 0,
    is_active        BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE document_types (
    id                  INTEGER      NOT NULL PRIMARY KEY,
    code                VARCHAR(50)  NOT NULL UNIQUE,   -- W2, FORM_1099, OFFER_LETTER, ...
    name                VARCHAR(120) NOT NULL,
    description         VARCHAR(255),
    category            VARCHAR(50)  NOT NULL,          -- document_categories.code
    applies_to          VARCHAR(10)  NOT NULL DEFAULT 'CASE',
    allowed_mime_types  VARCHAR(255),                   -- comma-separated; NULL = app default
    max_file_mb         INTEGER,
    sort_order          INTEGER      NOT NULL DEFAULT 0,
    is_active           BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at          TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_document_types_applies_to CHECK (applies_to IN ('CASE', 'STAFF')),
    CONSTRAINT fk_document_types_category FOREIGN KEY (category) REFERENCES document_categories (code)
);

CREATE TABLE case_stages (
    id               INTEGER      NOT NULL PRIMARY KEY,
    code             VARCHAR(50)  NOT NULL UNIQUE,      -- pending_review, docs_pending, ... (= tax_filings.status)
    name             VARCHAR(80)  NOT NULL,
    description      VARCHAR(255),
    client_status    VARCHAR(20)  NOT NULL,             -- what the client sees
    is_terminal      BOOLEAN      NOT NULL DEFAULT FALSE,
    sort_order       INTEGER      NOT NULL DEFAULT 0,
    is_active        BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_case_stages_client_status
        CHECK (client_status IN ('Submitted', 'In Progress', 'Completed', 'Closed', 'Amendment'))
);

CREATE TABLE chat_query_topics (
    id               INTEGER      NOT NULL PRIMARY KEY,
    code             VARCHAR(30)  NOT NULL UNIQUE,      -- FILING_STATUS, REFUND, ...
    name             VARCHAR(80)  NOT NULL,
    description      VARCHAR(255),
    sort_order       INTEGER      NOT NULL DEFAULT 0,
    is_active        BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);


-- =====================================================================
-- 2. IDENTITY
-- auth_accounts is the only table with credentials. Every account of
-- any kind has one user_profiles row. Kind tables hold only fields
-- specific to that kind.
-- =====================================================================

CREATE TABLE auth_accounts (
    id                  VARCHAR(36)  NOT NULL PRIMARY KEY,
    account_number      VARCHAR(20)  NOT NULL UNIQUE,   -- <number_prefix>-00000001
    email               VARCHAR(254) NOT NULL UNIQUE,
    password_hash       VARCHAR(512) NOT NULL,
    account_type        VARCHAR(30)  NOT NULL,
    is_active           BOOLEAN      NOT NULL DEFAULT TRUE,
    is_verified         BOOLEAN      NOT NULL DEFAULT FALSE,
    email_verified_at   TIMESTAMP,
    last_login_at       TIMESTAMP,
    failed_login_count  INTEGER      NOT NULL DEFAULT 0,
    locked_until        TIMESTAMP,
    created_at          TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_auth_accounts_type FOREIGN KEY (account_type) REFERENCES account_types (code)
);

CREATE TABLE auth_sessions (
    id                  VARCHAR(36)  NOT NULL PRIMARY KEY,
    account_id          VARCHAR(36)  NOT NULL,
    session_token_hash  VARCHAR(256) NOT NULL UNIQUE,
    ip_address          VARCHAR(45),
    user_agent          TEXT,
    expires_at          TIMESTAMP    NOT NULL,
    revoked_at          TIMESTAMP,
    last_activity_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at          TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_auth_sessions_account FOREIGN KEY (account_id) REFERENCES auth_accounts (id) ON DELETE CASCADE
);
CREATE INDEX ix_auth_sessions_account_id ON auth_sessions (account_id);

CREATE TABLE auth_refresh_tokens (
    id           VARCHAR(36)  NOT NULL PRIMARY KEY,
    account_id   VARCHAR(36)  NOT NULL,
    token_hash   VARCHAR(256) NOT NULL UNIQUE,
    expires_at   TIMESTAMP    NOT NULL,
    revoked_at   TIMESTAMP,
    created_at   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_auth_refresh_tokens_account FOREIGN KEY (account_id) REFERENCES auth_accounts (id) ON DELETE CASCADE
);
CREATE INDEX ix_auth_refresh_tokens_account_id ON auth_refresh_tokens (account_id);

CREATE TABLE auth_password_reset_tokens (
    id           VARCHAR(36)  NOT NULL PRIMARY KEY,
    account_id   VARCHAR(36)  NOT NULL,
    token_hash   VARCHAR(256) NOT NULL UNIQUE,
    expires_at   TIMESTAMP    NOT NULL,
    used_at      TIMESTAMP,
    created_at   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_auth_pwreset_account FOREIGN KEY (account_id) REFERENCES auth_accounts (id) ON DELETE CASCADE
);
CREATE INDEX ix_auth_password_reset_tokens_account_id ON auth_password_reset_tokens (account_id);

CREATE TABLE auth_email_verification_tokens (
    id           VARCHAR(36)  NOT NULL PRIMARY KEY,
    account_id   VARCHAR(36)  NOT NULL,
    token_hash   VARCHAR(256) NOT NULL UNIQUE,
    expires_at   TIMESTAMP    NOT NULL,
    verified_at  TIMESTAMP,
    created_at   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_auth_emailverify_account FOREIGN KEY (account_id) REFERENCES auth_accounts (id) ON DELETE CASCADE
);
CREATE INDEX ix_auth_email_verification_tokens_account_id ON auth_email_verification_tokens (account_id);

CREATE TABLE auth_login_attempts (
    id              VARCHAR(36)  NOT NULL PRIMARY KEY,
    account_id      VARCHAR(36),
    email           VARCHAR(254) NOT NULL,
    ip_address      VARCHAR(45),
    user_agent      TEXT,
    success         BOOLEAN      NOT NULL,
    failure_reason  VARCHAR(200),
    created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_auth_login_attempts_account FOREIGN KEY (account_id) REFERENCES auth_accounts (id) ON DELETE SET NULL
);
CREATE INDEX ix_auth_login_attempts_account_id ON auth_login_attempts (account_id);
CREATE INDEX ix_auth_login_attempts_email ON auth_login_attempts (email);

CREATE TABLE user_profiles (
    id               VARCHAR(36)  NOT NULL PRIMARY KEY,
    account_id       VARCHAR(36)  NOT NULL UNIQUE,
    first_name       VARCHAR(50)  NOT NULL,
    last_name        VARCHAR(50),
    phone            VARCHAR(25),
    profile_picture  VARCHAR(255),
    date_of_birth    DATE,
    address_line_1   VARCHAR(120),
    address_line_2   VARCHAR(120),
    city             VARCHAR(80),
    state_province   VARCHAR(80),
    postal_code      VARCHAR(20),
    country          VARCHAR(80),
    created_at       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_user_profiles_account FOREIGN KEY (account_id) REFERENCES auth_accounts (id) ON DELETE CASCADE
);

CREATE TABLE clients (
    id             VARCHAR(36)  NOT NULL PRIMARY KEY,
    account_id     VARCHAR(36)  NOT NULL UNIQUE,
    client_number  VARCHAR(20)  NOT NULL UNIQUE,
    created_at     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_clients_account FOREIGN KEY (account_id) REFERENCES auth_accounts (id) ON DELETE CASCADE
);

CREATE TABLE staff (
    id                     VARCHAR(36)  NOT NULL PRIMARY KEY,
    account_id             VARCHAR(36)  NOT NULL UNIQUE,
    staff_number           VARCHAR(20)  NOT NULL UNIQUE,
    job_title              VARCHAR(50),
    notifications_seen_at  TIMESTAMP,
    created_at             TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at             TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_staff_account FOREIGN KEY (account_id) REFERENCES auth_accounts (id) ON DELETE CASCADE
);

CREATE TABLE admins (
    id            VARCHAR(36)  NOT NULL PRIMARY KEY,
    account_id    VARCHAR(36)  NOT NULL UNIQUE,
    admin_number  VARCHAR(20)  NOT NULL UNIQUE,
    created_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_admins_account FOREIGN KEY (account_id) REFERENCES auth_accounts (id) ON DELETE CASCADE
);

CREATE TABLE hr (
    id          VARCHAR(36)  NOT NULL PRIMARY KEY,
    account_id  VARCHAR(36)  NOT NULL UNIQUE,
    hr_number   VARCHAR(20)  NOT NULL UNIQUE,
    department  VARCHAR(80),
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_hr_account FOREIGN KEY (account_id) REFERENCES auth_accounts (id) ON DELETE CASCADE
);


-- =====================================================================
-- 3. STAFF (roles and HR-managed records)
-- =====================================================================

CREATE TABLE staff_role_assignments (
    id                      VARCHAR(36)  NOT NULL PRIMARY KEY,
    staff_id                VARCHAR(36)  NOT NULL,
    role_id                 INTEGER      NOT NULL,
    is_primary              BOOLEAN      NOT NULL DEFAULT FALSE,
    assigned_by_account_id  VARCHAR(36),
    assigned_at             TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_staff_role UNIQUE (staff_id, role_id),
    CONSTRAINT fk_sra_staff FOREIGN KEY (staff_id) REFERENCES staff (id) ON DELETE CASCADE,
    CONSTRAINT fk_sra_role FOREIGN KEY (role_id) REFERENCES staff_roles (id),
    CONSTRAINT fk_sra_assigned_by FOREIGN KEY (assigned_by_account_id) REFERENCES auth_accounts (id) ON DELETE SET NULL
);

CREATE TABLE staff_employment_details (
    id                          VARCHAR(36)   NOT NULL PRIMARY KEY,
    staff_id                    VARCHAR(36)   NOT NULL UNIQUE,
    employee_number             VARCHAR(30)   NOT NULL UNIQUE,
    date_of_joining             DATE,
    employment_type             VARCHAR(30),           -- FULL_TIME, PART_TIME, CONTRACT, ...
    department                  VARCHAR(80),
    designation                 VARCHAR(80),
    reporting_manager_staff_id  VARCHAR(36),
    employment_status           VARCHAR(30)   NOT NULL DEFAULT 'ACTIVE',
    termination_date            DATE,
    current_salary              DECIMAL(12,2),
    updated_by_account_id       VARCHAR(36),
    updated_at                  TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_sed_staff FOREIGN KEY (staff_id) REFERENCES staff (id) ON DELETE CASCADE,
    CONSTRAINT fk_sed_manager FOREIGN KEY (reporting_manager_staff_id) REFERENCES staff (id) ON DELETE SET NULL,
    CONSTRAINT fk_sed_updated_by FOREIGN KEY (updated_by_account_id) REFERENCES auth_accounts (id) ON DELETE SET NULL
);

CREATE TABLE staff_documents (
    id                      VARCHAR(36)  NOT NULL PRIMARY KEY,
    document_number         VARCHAR(20)  NOT NULL UNIQUE,   -- SDOC-0000001
    staff_id                VARCHAR(36)  NOT NULL,
    document_type_id        INTEGER      NOT NULL,     -- document_types.applies_to = 'STAFF'
    original_filename       VARCHAR(255) NOT NULL,
    stored_filename         VARCHAR(255) NOT NULL,
    file_path               VARCHAR(500) NOT NULL,
    mime_type               VARCHAR(100) NOT NULL,
    file_size               INTEGER      NOT NULL,
    uploaded_by_account_id  VARCHAR(36),
    uploaded_at             TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expiry_date             DATE,
    notes                   TEXT,
    CONSTRAINT fk_staff_documents_staff FOREIGN KEY (staff_id) REFERENCES staff (id) ON DELETE CASCADE,
    CONSTRAINT fk_staff_documents_type FOREIGN KEY (document_type_id) REFERENCES document_types (id),
    CONSTRAINT fk_staff_documents_uploader FOREIGN KEY (uploaded_by_account_id) REFERENCES auth_accounts (id) ON DELETE SET NULL
);
CREATE INDEX ix_staff_documents_staff_id ON staff_documents (staff_id);

CREATE TABLE staff_salary_history (
    id                      VARCHAR(36)   NOT NULL PRIMARY KEY,
    staff_id                VARCHAR(36)   NOT NULL,
    effective_date          DATE          NOT NULL,
    previous_salary         DECIMAL(12,2),
    new_salary              DECIMAL(12,2) NOT NULL,
    hike_percentage         DECIMAL(5,2),
    reason                  VARCHAR(255),
    approved_by_account_id  VARCHAR(36),
    created_at              TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_ssh_staff FOREIGN KEY (staff_id) REFERENCES staff (id) ON DELETE CASCADE,
    CONSTRAINT fk_ssh_approved_by FOREIGN KEY (approved_by_account_id) REFERENCES auth_accounts (id) ON DELETE SET NULL
);
CREATE INDEX ix_staff_salary_history_staff_id ON staff_salary_history (staff_id);


-- =====================================================================
-- 4. TAX CASE (the existing tax_filings table, with lookups added)
-- =====================================================================

CREATE TABLE tax_filings (
    id                              VARCHAR(36)  NOT NULL PRIMARY KEY,
    case_number                     VARCHAR(30)  NOT NULL UNIQUE,    -- FLI_0000001
    client_id                       VARCHAR(36)  NOT NULL,
    tax_year_id                     INTEGER      NOT NULL,           -- was tax_year INTEGER
    tax_type_id                     INTEGER      NOT NULL,           -- was filing_type VARCHAR
    stage_code                      VARCHAR(50)  NOT NULL DEFAULT 'pending_review', -- was status VARCHAR
    filing_method                   VARCHAR(20),                     -- NULL until Review
    priority                        VARCHAR(20)  NOT NULL DEFAULT 'NORMAL',
    submitted_at                    TIMESTAMP,
    closed_at                       TIMESTAMP,

    -- 01 Basic information (intake snapshot)
    first_name                      VARCHAR(50)  NOT NULL,
    last_name                       VARCHAR(50)  NOT NULL,
    email                           VARCHAR(255) NOT NULL,
    phone                           VARCHAR(25),

    -- 02 Personal and filing details
    date_of_birth                   DATE,
    country_of_citizenship          VARCHAR(80),
    current_country_of_residence    VARCHAR(80),
    us_tax_residency_status         VARCHAR(50),
    filing_status                   VARCHAR(50),
    filed_us_taxes_before           VARCHAR(10),
    previous_tax_year_filed         INTEGER,
    address_line_1                  VARCHAR(120),
    address_line_2                  VARCHAR(120),
    city                            VARCHAR(80),
    state_province                  VARCHAR(80),
    postal_code                     VARCHAR(20),
    country                         VARCHAR(80),

    -- 03 Spouse information
    spouse_first_name               VARCHAR(50),
    spouse_last_name                VARCHAR(50),
    spouse_date_of_birth            DATE,
    spouse_email                    VARCHAR(255),
    spouse_phone                    VARCHAR(25),
    spouse_country_of_citizenship   VARCHAR(80),
    spouse_us_tax_residency_status  VARCHAR(50),

    -- 04, 05, 06, 08 Dynamic sections (JSON arrays stored as TEXT)
    dependents                      TEXT         NOT NULL,                -- app writes '[]' by default
    income_categories               TEXT         NOT NULL,                -- app writes '[]' by default
    deductions_credits              TEXT         NOT NULL,                -- app writes '[]' by default
    special_situations              TEXT         NOT NULL,                -- app writes '[]' by default

    -- 07 Previous tax information
    has_previous_return_copy        VARCHAR(10),
    received_irs_notice             VARCHAR(10),
    unresolved_tax_issues           VARCHAR(10),
    is_amended_return               VARCHAR(10),

    created_at                      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at                      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_tax_filings_client FOREIGN KEY (client_id) REFERENCES clients (id) ON DELETE CASCADE,
    CONSTRAINT fk_tax_filings_year FOREIGN KEY (tax_year_id) REFERENCES tax_years (id),
    CONSTRAINT fk_tax_filings_type FOREIGN KEY (tax_type_id) REFERENCES tax_types (id),
    CONSTRAINT fk_tax_filings_stage FOREIGN KEY (stage_code) REFERENCES case_stages (code),
    CONSTRAINT ck_tax_filings_method CHECK (filing_method IS NULL OR filing_method IN ('PAPER_FILING', 'FORM_8879')),
    CONSTRAINT ck_tax_filings_priority CHECK (priority IN ('LOW', 'NORMAL', 'HIGH', 'URGENT'))
);
CREATE INDEX ix_tax_filings_client_id ON tax_filings (client_id);
CREATE INDEX ix_tax_filings_year_stage ON tax_filings (tax_year_id, stage_code);

CREATE TABLE case_assignments (
    id                      VARCHAR(36)  NOT NULL PRIMARY KEY,
    case_id                 VARCHAR(36)  NOT NULL,
    staff_id                VARCHAR(36)  NOT NULL,
    role_id                 INTEGER      NOT NULL,
    assigned_by_account_id  VARCHAR(36),
    assigned_at             TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    unassigned_at           TIMESTAMP,
    status                  VARCHAR(10)  NOT NULL DEFAULT 'active',
    CONSTRAINT fk_ca_case FOREIGN KEY (case_id) REFERENCES tax_filings (id) ON DELETE CASCADE,
    CONSTRAINT fk_ca_staff FOREIGN KEY (staff_id) REFERENCES staff (id),
    CONSTRAINT fk_ca_role FOREIGN KEY (role_id) REFERENCES staff_roles (id),
    CONSTRAINT fk_ca_assigned_by FOREIGN KEY (assigned_by_account_id) REFERENCES auth_accounts (id) ON DELETE SET NULL,
    CONSTRAINT ck_ca_status CHECK (status IN ('active', 'ended'))
);
CREATE INDEX ix_case_assignments_case_id ON case_assignments (case_id);
CREATE INDEX ix_case_assignments_staff_status ON case_assignments (staff_id, status);   -- "My Queue"
-- One active assignment per role per case. Partial indexes are not
-- portable, so enforce this in the service layer, or on PostgreSQL /
-- SQLite add:
--   CREATE UNIQUE INDEX uq_case_assignments_active
--       ON case_assignments (case_id, role_id) WHERE status = 'active';

CREATE TABLE case_stage_history (
    id                     VARCHAR(36)  NOT NULL PRIMARY KEY,
    case_id                VARCHAR(36)  NOT NULL,
    from_stage_code        VARCHAR(50),                  -- NULL for the first stage
    to_stage_code          VARCHAR(50)  NOT NULL,
    changed_by_account_id  VARCHAR(36),
    comment                TEXT,
    created_at             TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_csh_case FOREIGN KEY (case_id) REFERENCES tax_filings (id) ON DELETE CASCADE,
    CONSTRAINT fk_csh_from FOREIGN KEY (from_stage_code) REFERENCES case_stages (code),
    CONSTRAINT fk_csh_to FOREIGN KEY (to_stage_code) REFERENCES case_stages (code),
    CONSTRAINT fk_csh_changed_by FOREIGN KEY (changed_by_account_id) REFERENCES auth_accounts (id) ON DELETE SET NULL
);
CREATE INDEX ix_case_stage_history_case_id ON case_stage_history (case_id, created_at);


-- =====================================================================
-- 5. DOCUMENTS (existing filing_documents and document_comments)
-- =====================================================================

CREATE TABLE required_documents (
    id                VARCHAR(36)  NOT NULL PRIMARY KEY,
    tax_year_id       INTEGER      NOT NULL,
    tax_type_id       INTEGER      NOT NULL,
    document_type_id  INTEGER      NOT NULL,
    is_required       BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at        TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_required_documents UNIQUE (tax_year_id, tax_type_id, document_type_id),
    CONSTRAINT fk_rd_year FOREIGN KEY (tax_year_id) REFERENCES tax_years (id),
    CONSTRAINT fk_rd_type FOREIGN KEY (tax_type_id) REFERENCES tax_types (id),
    CONSTRAINT fk_rd_doc_type FOREIGN KEY (document_type_id) REFERENCES document_types (id)
);

CREATE TABLE filing_documents (
    id                      VARCHAR(36)  NOT NULL PRIMARY KEY,
    document_number         VARCHAR(20)  NOT NULL UNIQUE,   -- DOC-0000001, one per uploaded version
    filing_id               VARCHAR(36)  NOT NULL,
    document_group_id       VARCHAR(36)  NOT NULL,     -- groups versions of one document
    document_type_id        INTEGER,                   -- NULL only for legacy rows before backfill
    category                VARCHAR(50)  NOT NULL,     -- kept during migration; comes from the type
    document_name           VARCHAR(120) NOT NULL,
    original_filename       VARCHAR(255) NOT NULL,
    stored_filename         VARCHAR(255) NOT NULL,
    file_path               VARCHAR(500) NOT NULL,
    file_size               INTEGER      NOT NULL,
    mime_type               VARCHAR(100) NOT NULL,
    version                 INTEGER      NOT NULL DEFAULT 1,
    is_latest               BOOLEAN      NOT NULL DEFAULT TRUE,
    status                  VARCHAR(50)  NOT NULL DEFAULT 'pending_review',
    rejection_reason        TEXT,
    uploaded_by_account_id  VARCHAR(36)  NOT NULL,     -- was uploaded_by_type + uploaded_by_id
    uploaded_at             TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    reviewed_by_account_id  VARCHAR(36),               -- was reviewed_by_id
    reviewed_at             TIMESTAMP,
    CONSTRAINT fk_fd_filing FOREIGN KEY (filing_id) REFERENCES tax_filings (id) ON DELETE CASCADE,
    CONSTRAINT fk_fd_type FOREIGN KEY (document_type_id) REFERENCES document_types (id),
    CONSTRAINT fk_fd_uploader FOREIGN KEY (uploaded_by_account_id) REFERENCES auth_accounts (id),
    CONSTRAINT fk_fd_reviewer FOREIGN KEY (reviewed_by_account_id) REFERENCES auth_accounts (id) ON DELETE SET NULL,
    CONSTRAINT ck_fd_status CHECK (status IN ('pending_review', 'accepted', 'rejected_reupload_requested', 'superseded'))
);
CREATE INDEX ix_filing_documents_filing_id ON filing_documents (filing_id);
CREATE INDEX ix_filing_documents_group ON filing_documents (document_group_id, is_latest);

CREATE TABLE document_comments (
    id                 VARCHAR(36)  NOT NULL PRIMARY KEY,
    filing_id          VARCHAR(36)  NOT NULL,
    document_group_id  VARCHAR(36)  NOT NULL,
    document_id        VARCHAR(36),                    -- version the comment is about
    kind               VARCHAR(20)  NOT NULL DEFAULT 'note',
    body               TEXT         NOT NULL,
    author_type        VARCHAR(30)  NOT NULL,          -- snapshot of account_types.code
    author_account_id  VARCHAR(36)  NOT NULL,
    author_name        VARCHAR(80)  NOT NULL,          -- snapshot at time of writing
    created_at         TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_dc_filing FOREIGN KEY (filing_id) REFERENCES tax_filings (id) ON DELETE CASCADE,
    CONSTRAINT fk_dc_document FOREIGN KEY (document_id) REFERENCES filing_documents (id) ON DELETE SET NULL,
    CONSTRAINT fk_dc_author FOREIGN KEY (author_account_id) REFERENCES auth_accounts (id),
    CONSTRAINT ck_dc_kind CHECK (kind IN ('rejection', 'reply', 'reupload', 'note', 'accepted'))
);
CREATE INDEX ix_document_comments_filing_id ON document_comments (filing_id);
CREATE INDEX ix_document_comments_group ON document_comments (document_group_id, created_at);


-- =====================================================================
-- 6. IRS FILING (Form 8879 cases only)
-- =====================================================================

CREATE TABLE irs_submissions (
    id                       VARCHAR(36)  NOT NULL PRIMARY KEY,
    submission_number        VARCHAR(30)  NOT NULL UNIQUE,
    case_id                  VARCHAR(36)  NOT NULL,
    submitted_by_account_id  VARCHAR(36),
    irs_submission_id        VARCHAR(50),
    status                   VARCHAR(20)  NOT NULL DEFAULT 'pending',
    submitted_at             TIMESTAMP,
    created_at               TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at               TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_irs_sub_case FOREIGN KEY (case_id) REFERENCES tax_filings (id) ON DELETE CASCADE,
    CONSTRAINT fk_irs_sub_by FOREIGN KEY (submitted_by_account_id) REFERENCES auth_accounts (id) ON DELETE SET NULL,
    CONSTRAINT ck_irs_sub_status CHECK (status IN ('pending', 'submitted', 'accepted', 'rejected'))
);
CREATE INDEX ix_irs_submissions_case_id ON irs_submissions (case_id);

CREATE TABLE acknowledgments (
    id                      VARCHAR(36)  NOT NULL PRIMARY KEY,
    ack_number              VARCHAR(30)  NOT NULL UNIQUE,
    submission_id           VARCHAR(36)  NOT NULL,
    recorded_by_account_id  VARCHAR(36),
    irs_ack_number          VARCHAR(50),
    status                  VARCHAR(20)  NOT NULL,
    received_at             TIMESTAMP,
    message                 TEXT,
    created_at              TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_ack_submission FOREIGN KEY (submission_id) REFERENCES irs_submissions (id) ON DELETE CASCADE,
    CONSTRAINT fk_ack_recorded_by FOREIGN KEY (recorded_by_account_id) REFERENCES auth_accounts (id) ON DELETE SET NULL,
    CONSTRAINT ck_ack_status CHECK (status IN ('accepted', 'rejected'))
);
CREATE INDEX ix_acknowledgments_submission_id ON acknowledgments (submission_id);


-- =====================================================================
-- 7. FINANCIAL
-- =====================================================================

CREATE TABLE services (
    id            VARCHAR(36)   NOT NULL PRIMARY KEY,
    service_code  VARCHAR(30)   NOT NULL UNIQUE,
    name          VARCHAR(120)  NOT NULL,
    description   TEXT,
    base_price    DECIMAL(12,2) NOT NULL,
    is_active     BOOLEAN       NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE case_services (
    id            VARCHAR(36)   NOT NULL PRIMARY KEY,
    case_id       VARCHAR(36)   NOT NULL,
    service_id    VARCHAR(36)   NOT NULL,
    quantity      INTEGER       NOT NULL DEFAULT 1,
    unit_price    DECIMAL(12,2) NOT NULL,              -- copied from services.base_price
    total_amount  DECIMAL(12,2) NOT NULL,
    created_at    TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_cs_case FOREIGN KEY (case_id) REFERENCES tax_filings (id) ON DELETE CASCADE,
    CONSTRAINT fk_cs_service FOREIGN KEY (service_id) REFERENCES services (id),
    CONSTRAINT ck_cs_quantity CHECK (quantity > 0)
);
CREATE INDEX ix_case_services_case_id ON case_services (case_id);

CREATE TABLE invoices (
    id               VARCHAR(36)   NOT NULL PRIMARY KEY,
    invoice_number   VARCHAR(30)   NOT NULL UNIQUE,
    client_id        VARCHAR(36)   NOT NULL,
    case_id          VARCHAR(36)   NOT NULL,
    subtotal         DECIMAL(12,2) NOT NULL,
    discount_amount  DECIMAL(12,2) NOT NULL DEFAULT 0,
    tax_amount       DECIMAL(12,2) NOT NULL DEFAULT 0,
    total_amount     DECIMAL(12,2) NOT NULL,
    status           VARCHAR(20)   NOT NULL DEFAULT 'draft',
    invoice_date     DATE          NOT NULL,
    due_date         DATE,
    created_at       TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_inv_client FOREIGN KEY (client_id) REFERENCES clients (id),
    CONSTRAINT fk_inv_case FOREIGN KEY (case_id) REFERENCES tax_filings (id),
    CONSTRAINT ck_inv_status CHECK (status IN ('draft', 'issued', 'paid', 'partially_paid', 'void'))
);
CREATE INDEX ix_invoices_case_id ON invoices (case_id);
CREATE INDEX ix_invoices_client_id ON invoices (client_id);

CREATE TABLE payments (
    id                     VARCHAR(36)   NOT NULL PRIMARY KEY,
    payment_number         VARCHAR(30)   NOT NULL UNIQUE,
    invoice_id             VARCHAR(36)   NOT NULL,
    client_id              VARCHAR(36)   NOT NULL,
    amount                 DECIMAL(12,2) NOT NULL,
    payment_method         VARCHAR(30)   NOT NULL,
    transaction_reference  VARCHAR(100),
    status                 VARCHAR(20)   NOT NULL DEFAULT 'pending',
    paid_at                TIMESTAMP,
    created_at             TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_pay_invoice FOREIGN KEY (invoice_id) REFERENCES invoices (id),
    CONSTRAINT fk_pay_client FOREIGN KEY (client_id) REFERENCES clients (id),
    CONSTRAINT ck_pay_status CHECK (status IN ('pending', 'succeeded', 'failed', 'refunded')),
    CONSTRAINT ck_pay_amount CHECK (amount > 0)
);
CREATE INDEX ix_payments_invoice_id ON payments (invoice_id);


-- =====================================================================
-- 8. SYSTEM
-- entity_type + entity_id stay open-ended on purpose: these rows can
-- point at any record.
-- =====================================================================

CREATE TABLE audit_logs (
    id                VARCHAR(36)  NOT NULL PRIMARY KEY,
    actor_account_id  VARCHAR(36),                     -- NULL for system jobs
    action            VARCHAR(50)  NOT NULL,
    entity_type       VARCHAR(50)  NOT NULL,           -- tax_filing, filing_document, invoice, ...
    entity_id         VARCHAR(36)  NOT NULL,
    old_values        TEXT,                            -- JSON
    new_values        TEXT,                            -- JSON
    ip_address        VARCHAR(45),
    created_at        TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_audit_actor FOREIGN KEY (actor_account_id) REFERENCES auth_accounts (id) ON DELETE SET NULL
);
CREATE INDEX ix_audit_logs_entity ON audit_logs (entity_type, entity_id);
CREATE INDEX ix_audit_logs_actor ON audit_logs (actor_account_id, created_at);

CREATE TABLE notifications (
    id                    VARCHAR(36)  NOT NULL PRIMARY KEY,
    recipient_account_id  VARCHAR(36)  NOT NULL,
    type                  VARCHAR(50)  NOT NULL,
    title                 VARCHAR(150) NOT NULL,
    message               TEXT,
    entity_type           VARCHAR(50),
    entity_id             VARCHAR(36),
    is_read               BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at            TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    read_at               TIMESTAMP,
    CONSTRAINT fk_notifications_recipient FOREIGN KEY (recipient_account_id) REFERENCES auth_accounts (id) ON DELETE CASCADE
);
CREATE INDEX ix_notifications_recipient ON notifications (recipient_account_id, is_read, created_at);


-- =====================================================================
-- 8b. MESSAGING
-- DIRECT = two internal members, GROUP = named internal group,
-- CASE = client + case team on one filing, QUERY = a client question.
-- case_id is set only when the conversation is about a filing.
-- Who may read or post is checked in the chat service. Nothing is
-- hard-deleted: a daily job sets hidden_at once hide_after passes, and
-- hidden threads stay here for audit.
-- =====================================================================

CREATE TABLE chat_threads (
    id                      VARCHAR(36)  NOT NULL PRIMARY KEY,
    thread_number           VARCHAR(20)  NOT NULL UNIQUE,   -- MSG-0000001
    kind                    VARCHAR(10)  NOT NULL,
    name                    VARCHAR(100),                   -- GROUP only
    case_id                 VARCHAR(36),                    -- set only when about a filing; required for CASE
    topic_id                INTEGER,                        -- QUERY only
    subject                 VARCHAR(150),                   -- QUERY only
    direct_key              VARCHAR(110) UNIQUE,            -- DIRECT only: "smallerId:largerId" or "smallerId:largerId:caseId"
    status                  VARCHAR(10)  NOT NULL DEFAULT 'open',
    owner_account_id        VARCHAR(36),                    -- QUERY: who handles it; NULL = unclaimed
    created_by_account_id   VARCHAR(36)  NOT NULL,
    last_message_at         TIMESTAMP,
    last_message_preview    VARCHAR(160),                   -- last client-visible message
    resolved_at             TIMESTAMP,
    resolved_by_account_id  VARCHAR(36),
    hide_after              TIMESTAMP,                      -- daily job hides the thread after this; NULL = stays visible
    hidden_at               TIMESTAMP,                      -- set by the job; kept for audit, not shown in portals
    created_at              TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at              TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_ct_case FOREIGN KEY (case_id) REFERENCES tax_filings (id) ON DELETE CASCADE,
    CONSTRAINT fk_ct_topic FOREIGN KEY (topic_id) REFERENCES chat_query_topics (id),
    CONSTRAINT fk_ct_owner FOREIGN KEY (owner_account_id) REFERENCES auth_accounts (id) ON DELETE SET NULL,
    CONSTRAINT fk_ct_creator FOREIGN KEY (created_by_account_id) REFERENCES auth_accounts (id),
    CONSTRAINT fk_ct_resolver FOREIGN KEY (resolved_by_account_id) REFERENCES auth_accounts (id) ON DELETE SET NULL,
    CONSTRAINT ck_ct_kind CHECK (kind IN ('DIRECT', 'GROUP', 'CASE', 'QUERY')),
    CONSTRAINT ck_ct_status CHECK (status IN ('open', 'resolved', 'closed')),
    CONSTRAINT ck_ct_shape CHECK (
        (kind = 'DIRECT' AND direct_key IS NOT NULL AND topic_id IS NULL)
     OR (kind = 'GROUP'  AND name IS NOT NULL AND topic_id IS NULL AND direct_key IS NULL)
     OR (kind = 'CASE'   AND case_id IS NOT NULL AND direct_key IS NULL AND topic_id IS NULL)
     OR (kind = 'QUERY'  AND topic_id IS NOT NULL AND subject IS NOT NULL AND direct_key IS NULL)
    )
);
CREATE INDEX ix_chat_threads_case ON chat_threads (case_id, kind);
CREATE INDEX ix_chat_threads_queue ON chat_threads (kind, status, owner_account_id);   -- unclaimed / my queries
CREATE INDEX ix_chat_threads_hide ON chat_threads (hidden_at, hide_after);             -- daily hiding job
-- One CASE thread per case. Partial indexes are not portable, so enforce
-- this in the service layer, or on PostgreSQL / SQLite add:
--   CREATE UNIQUE INDEX uq_chat_threads_case
--       ON chat_threads (case_id) WHERE kind = 'CASE';
-- SQL Server allows only one NULL in a UNIQUE column: replace the
-- direct_key UNIQUE with a filtered index (WHERE direct_key IS NOT NULL).

CREATE TABLE chat_participants (
    id            VARCHAR(36)  NOT NULL PRIMARY KEY,
    thread_id     VARCHAR(36)  NOT NULL,
    account_id    VARCHAR(36)  NOT NULL,
    member_role   VARCHAR(10)  NOT NULL DEFAULT 'member',   -- GROUP: owner | member
    added_reason  VARCHAR(20)  NOT NULL DEFAULT 'member',
    joined_at     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    left_at       TIMESTAMP,                                -- NULL = active member
    last_read_at  TIMESTAMP,                                -- unread = messages after this
    is_muted      BOOLEAN      NOT NULL DEFAULT FALSE,
    CONSTRAINT uq_cp_thread_account UNIQUE (thread_id, account_id),
    CONSTRAINT fk_cp_thread FOREIGN KEY (thread_id) REFERENCES chat_threads (id) ON DELETE CASCADE,
    CONSTRAINT fk_cp_account FOREIGN KEY (account_id) REFERENCES auth_accounts (id),
    CONSTRAINT ck_cp_role CHECK (member_role IN ('owner', 'member')),
    CONSTRAINT ck_cp_reason CHECK (added_reason IN ('member', 'client', 'case_assignment', 'admin_joined', 'query_owner'))
);
CREATE INDEX ix_chat_participants_inbox ON chat_participants (account_id, left_at);

CREATE TABLE chat_messages (
    id                     VARCHAR(36)  NOT NULL PRIMARY KEY,
    thread_id              VARCHAR(36)  NOT NULL,
    sender_account_id      VARCHAR(36),                     -- NULL for system messages
    sender_type            VARCHAR(30),                     -- snapshot of account_types.code
    sender_name            VARCHAR(80),                     -- snapshot at time of writing
    kind                   VARCHAR(10)  NOT NULL DEFAULT 'text',
    visibility             VARCHAR(10)  NOT NULL DEFAULT 'all',   -- internal = staff note, never shown to the client
    body                   TEXT         NOT NULL,
    reply_to_message_id    VARCHAR(36),
    edited_at              TIMESTAMP,
    deleted_at             TIMESTAMP,                       -- soft delete; text stays for audit
    deleted_by_account_id  VARCHAR(36),
    created_at             TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_cm_thread FOREIGN KEY (thread_id) REFERENCES chat_threads (id) ON DELETE CASCADE,
    CONSTRAINT fk_cm_sender FOREIGN KEY (sender_account_id) REFERENCES auth_accounts (id),
    CONSTRAINT fk_cm_reply FOREIGN KEY (reply_to_message_id) REFERENCES chat_messages (id),
    CONSTRAINT fk_cm_deleter FOREIGN KEY (deleted_by_account_id) REFERENCES auth_accounts (id),
    CONSTRAINT ck_cm_kind CHECK (kind IN ('text', 'system')),
    CONSTRAINT ck_cm_visibility CHECK (visibility IN ('all', 'internal'))
);
CREATE INDEX ix_chat_messages_thread ON chat_messages (thread_id, created_at);

CREATE TABLE chat_attachments (
    id                  VARCHAR(36)  NOT NULL PRIMARY KEY,
    message_id          VARCHAR(36)  NOT NULL,
    original_filename   VARCHAR(255) NOT NULL,
    stored_filename     VARCHAR(255) NOT NULL,
    file_path           VARCHAR(500) NOT NULL,
    mime_type           VARCHAR(100) NOT NULL,
    file_size           INTEGER      NOT NULL,
    filing_document_id  VARCHAR(36),                        -- set by "Save to case documents" (a copy)
    created_at          TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_cat_message FOREIGN KEY (message_id) REFERENCES chat_messages (id) ON DELETE CASCADE,
    CONSTRAINT fk_cat_document FOREIGN KEY (filing_document_id) REFERENCES filing_documents (id) ON DELETE SET NULL
);
CREATE INDEX ix_chat_attachments_message_id ON chat_attachments (message_id);


-- =====================================================================
-- 8c. QUERY INDEXES
-- One per query the app runs; see docs/DATABASE_POLICIES.md section 7.
-- Written for this file's target columns. The live database still has
-- tax_filings.tax_year / status and filing_documents.uploaded_by_type, so
-- migration b8d0f2a4c6e9 indexes those; the year/stage index and the two
-- document_group_id indexes already appear with their tables above.
-- =====================================================================

CREATE INDEX ix_tax_filings_client_year ON tax_filings (client_id, tax_year_id, created_at);
CREATE INDEX ix_tax_filings_stage_created ON tax_filings (stage_code, created_at);
CREATE INDEX ix_tax_filings_created ON tax_filings (created_at);
CREATE INDEX ix_tax_filings_updated ON tax_filings (updated_at);
CREATE INDEX ix_filing_documents_filing_latest ON filing_documents (filing_id, is_latest, uploaded_at);
CREATE INDEX ix_filing_documents_uploaded ON filing_documents (uploaded_at);
CREATE INDEX ix_document_comments_filing_created ON document_comments (filing_id, created_at);
CREATE INDEX ix_document_comments_author_kind ON document_comments (author_type, kind, created_at);
CREATE INDEX ix_clients_created ON clients (created_at);
CREATE INDEX ix_staff_created ON staff (created_at);
CREATE INDEX ix_auth_refresh_tokens_account_revoked ON auth_refresh_tokens (account_id, revoked_at);
CREATE INDEX ix_case_assignments_case_status ON case_assignments (case_id, status);
CREATE INDEX ix_invoices_status_due ON invoices (status, due_date);
CREATE INDEX ix_payments_status_paid ON payments (status, paid_at);
CREATE INDEX ix_staff_documents_expiry ON staff_documents (expiry_date);
CREATE INDEX ix_staff_salary_history_staff_date ON staff_salary_history (staff_id, effective_date);
CREATE INDEX ix_staff_employment_status ON staff_employment_details (employment_status);
CREATE INDEX ix_audit_logs_created ON audit_logs (created_at);

-- PostgreSQL only: trigram indexes for ILIKE '%term%' search boxes.
--   CREATE EXTENSION IF NOT EXISTS pg_trgm;
--   CREATE INDEX ix_tax_filings_case_number_trgm ON tax_filings USING gin (case_number gin_trgm_ops);
--   CREATE INDEX ix_tax_filings_email_trgm ON tax_filings USING gin (email gin_trgm_ops);
--   CREATE INDEX ix_tax_filings_first_name_trgm ON tax_filings USING gin (first_name gin_trgm_ops);
--   CREATE INDEX ix_tax_filings_last_name_trgm ON tax_filings USING gin (last_name gin_trgm_ops);
--   CREATE INDEX ix_clients_client_number_trgm ON clients USING gin (client_number gin_trgm_ops);
--   CREATE INDEX ix_clients_first_name_trgm ON clients USING gin (first_name gin_trgm_ops);
--   CREATE INDEX ix_clients_last_name_trgm ON clients USING gin (last_name gin_trgm_ops);
--   CREATE INDEX ix_staff_staff_number_trgm ON staff USING gin (staff_number gin_trgm_ops);
--   CREATE INDEX ix_staff_first_name_trgm ON staff USING gin (first_name gin_trgm_ops);
--   CREATE INDEX ix_staff_last_name_trgm ON staff USING gin (last_name gin_trgm_ops);


-- =====================================================================
-- 9. SEED DATA
-- =====================================================================

-- Readable number formats. On an existing database, set current_value to
-- the highest number already in use for each kind.
INSERT INTO id_sequences (name, prefix, width, current_value) VALUES
    ('ACCOUNT_CLIENT', 'CLT-',  8, 0),
    ('ACCOUNT_STAFF',  'STF-',  8, 0),
    ('ACCOUNT_ADMIN',  'ADM-',  8, 0),
    ('ACCOUNT_HR',     'HR-',   8, 0),
    ('CLIENT',         'CLI-',  8, 0),
    ('STAFF',          'STF-',  8, 0),
    ('ADMIN',          'ADM-',  8, 0),
    ('HR',             'HR-',   8, 0),
    ('EMPLOYEE',       'EMP-',  6, 0),
    ('CASE',           'FLI_',  7, 0),
    ('DOCUMENT',       'DOC-',  7, 0),
    ('STAFF_DOCUMENT', 'SDOC-', 7, 0),
    ('IRS_SUBMISSION', 'SUB-',  7, 0),
    ('ACKNOWLEDGMENT', 'ACK-',  7, 0),
    ('INVOICE',        'INV-',  7, 0),
    ('PAYMENT',        'PAY-',  7, 0),
    ('CHAT_THREAD',    'MSG-',  7, 0);

-- =====================================================================
-- SEED DATA FOR LOOKUPS
-- Values match the current enums and code. Extend these lists by adding
-- rows; never reuse or change a `code` once it has been used.
-- =====================================================================

INSERT INTO account_types (id, code, name, number_prefix, portal_path, has_case_access, is_internal, sort_order) VALUES
    (1, 'CLIENT', 'Client', 'CLT', '/client', TRUE,  FALSE, 1),
    (2, 'STAFF',  'Staff',  'STF', '/staff',  TRUE,  TRUE,  2),
    (3, 'ADMIN',  'Admin',  'ADM', '/admin',  TRUE,  TRUE,  3),
    (4, 'HR',     'HR',     'HR',  '/hr',     FALSE, TRUE,  4);

-- HR and ADMIN were in the StaffRole enum. They are account types now.
INSERT INTO staff_roles (id, code, name, description, sort_order) VALUES
    (1, 'INITIATOR', 'Initiator', 'Checks intake and requests missing information', 1),
    (2, 'PREPARER',  'Preparer',  'Prepares the return',                          2),
    (3, 'REVIEWER',  'Reviewer',  'Reviews the prepared return',                  3),
    (4, 'MANAGER',   'Manager',   'Oversees cases and assignments',               4);

-- Matches dashboard._available_tax_years(): current year plus 4 prior years.
INSERT INTO tax_years (id, year, name, is_open, is_default, sort_order) VALUES
    (1, 2026, 'Tax year 2026', TRUE, FALSE, 1),
    (2, 2025, 'Tax year 2025', TRUE, TRUE,  2),
    (3, 2024, 'Tax year 2024', TRUE, FALSE, 3),
    (4, 2023, 'Tax year 2023', TRUE, FALSE, 4),
    (5, 2022, 'Tax year 2022', TRUE, FALSE, 5);

-- Codes are the values tax_filings.filing_type already stores.
INSERT INTO tax_types (id, code, name, sort_order) VALUES
    (1, 'individual', 'Individual (1040)',      1),
    (2, 'business',   'Business (1065 / 1120)', 2),
    (3, 'estate',     'Estate',                 3),
    (4, 'non_profit', 'Non-profit',             4),
    (5, 'amended',    'Amended return',         5);

-- Codes are the values filing_documents.category already stores.
INSERT INTO document_categories (id, code, name, sort_order) VALUES
    (1,  'Personal',            'Personal',           1),
    (2,  'Income',              'Income (W-2, 1099)', 2),
    (3,  'Employment',          'Employment',         3),
    (4,  'Investments',         'Investments',        4),
    (5,  'Deductions',          'Deductions',         5),
    (6,  'Credits',             'Credits',            6),
    (7,  'Foreign_Information', 'Foreign info',       7),
    (8,  'Dependents',          'Dependents',         8),
    (9,  'Property',            'Property',           9),
    (10, 'Business',            'Business',           10),
    (11, 'Other',               'Other',              11);

-- Categories match the ones the client documents page uses. The list is
-- a starting point; the full seed list is still an open item.
INSERT INTO document_types (id, code, name, category, applies_to, sort_order) VALUES
    (1,  'PASSPORT',        'Passport / ID',          'Personal',   'CASE',  1),
    (2,  'SSN_ITIN',        'SSN or ITIN letter',     'Personal',   'CASE',  2),
    (3,  'W2',              'Form W-2',               'Income',     'CASE',  3),
    (4,  'FORM_1099',       'Form 1099',              'Income',     'CASE',  4),
    (5,  'FORM_1098',       'Form 1098 (mortgage)',   'Deductions', 'CASE',  5),
    (6,  'PRIOR_RETURN',    'Prior year return',      'Other',      'CASE',  6),
    (7,  'OTHER',           'Other document',         'Other',      'CASE',  7),
    (8,  'OFFER_LETTER',    'Offer letter',           'Employment', 'STAFF', 8),
    (9,  'ID_PROOF',        'ID proof',               'Employment', 'STAFF', 9),
    (10, 'CONTRACT',        'Employment contract',    'Employment', 'STAFF', 10);

-- The staff workflow, in pipeline order. Codes are the values tax_filings.status stores.
INSERT INTO case_stages (id, code, name, client_status, is_terminal, sort_order) VALUES
    (1 , 'pending_review'        , 'Registered'            , 'Submitted'  , FALSE, 1),
    (2 , 'info_pending'          , 'Info Pending'          , 'In Progress', FALSE, 2),
    (3 , 'docs_pending'          , 'Docs Pending'          , 'In Progress', FALSE, 3),
    (4 , 'docs_received'         , 'Docs Received'         , 'In Progress', FALSE, 4),
    (5 , 'in_progress'           , 'In Progress'           , 'In Progress', FALSE, 5),
    (6 , 'drip'                  , 'DRIP'                  , 'In Progress', FALSE, 6),
    (7 , 'preparation'           , 'Preparation'           , 'In Progress', FALSE, 7),
    (8 , 'review'                , 'Review'                , 'In Progress', FALSE, 8),
    (9 , 'payment_pending'       , 'Payment Pending'       , 'In Progress', FALSE, 9),
    (10, 'draft_uploading'       , 'Draft Uploading'       , 'In Progress', FALSE, 10),
    (11, 'client_review'         , 'Client Review'         , 'In Progress', FALSE, 11),
    (12, 'rev_doc_rej'           , 'Rev Doc Rej'           , 'In Progress', FALSE, 12),
    (13, 'form_8879'             , 'Form 8879'             , 'In Progress', FALSE, 13),
    (14, 'e_filing'              , 'E-Filing'              , 'In Progress', FALSE, 14),
    (15, 'paper_filing'          , 'Paper Filing'          , 'In Progress', FALSE, 15),
    (16, 'paper_filing_coa'      , 'Paper Filing (COA)'    , 'In Progress', FALSE, 16),
    (17, 'state_filing'          , 'State Filing'          , 'In Progress', FALSE, 17),
    (18, 'signed_docs_uploaded'  , 'Signed Docs Uploaded'  , 'In Progress', FALSE, 18),
    (19, 'complete'              , 'Completed'             , 'Completed'  , TRUE , 19),
    (20, 'amendments'            , 'Amendments'            , 'Amendment'  , FALSE, 20);

-- Topics a client picks when asking a question.
INSERT INTO chat_query_topics (id, code, name, sort_order) VALUES
    (1, 'FILING_STATUS', 'Filing status',     1),
    (2, 'DOCUMENTS',     'Documents',         2),
    (3, 'PAYMENT',       'Payment & invoice', 3),
    (4, 'REFUND',        'Refund',            4),
    (5, 'IRS_NOTICE',    'IRS notice',        5),
    (6, 'GENERAL',       'Other question',    6);
