"""add tax_filings table

Revision ID: 3e0224cd65e9
Revises: 7a4d2b1c9f10
Create Date: 2026-08-31 12:32:40.488148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3e0224cd65e9'
down_revision: Union[str, None] = '7a4d2b1c9f10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tax_filings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('tax_year', sa.Integer(), nullable=False),
    sa.Column('filing_type', sa.String(length=50), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=25), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('country_of_citizenship', sa.String(length=80), nullable=True),
    sa.Column('current_country_of_residence', sa.String(length=80), nullable=True),
    sa.Column('us_tax_residency_status', sa.String(length=50), nullable=True),
    sa.Column('filing_status', sa.String(length=50), nullable=True),
    sa.Column('filed_us_taxes_before', sa.String(length=10), nullable=True),
    sa.Column('previous_tax_year_filed', sa.Integer(), nullable=True),
    sa.Column('address_line_1', sa.String(length=120), nullable=True),
    sa.Column('address_line_2', sa.String(length=120), nullable=True),
    sa.Column('city', sa.String(length=80), nullable=True),
    sa.Column('state_province', sa.String(length=80), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=80), nullable=True),
    sa.Column('spouse_first_name', sa.String(length=50), nullable=True),
    sa.Column('spouse_last_name', sa.String(length=50), nullable=True),
    sa.Column('spouse_date_of_birth', sa.Date(), nullable=True),
    sa.Column('spouse_email', sa.String(length=255), nullable=True),
    sa.Column('spouse_phone', sa.String(length=25), nullable=True),
    sa.Column('spouse_country_of_citizenship', sa.String(length=80), nullable=True),
    sa.Column('spouse_us_tax_residency_status', sa.String(length=50), nullable=True),
    sa.Column('dependents', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('income_categories', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('deductions_credits', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('special_situations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('has_previous_return_copy', sa.String(length=10), nullable=True),
    sa.Column('received_irs_notice', sa.String(length=10), nullable=True),
    sa.Column('unresolved_tax_issues', sa.String(length=10), nullable=True),
    sa.Column('is_amended_return', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tax_filings_client_id'), 'tax_filings', ['client_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tax_filings_client_id'), table_name='tax_filings')
    op.drop_table('tax_filings')
    # ### end Alembic commands ###
