"""add filing_documents table and versioning

Revision ID: 83f96ca208c6
Revises: e922b47ac98b
Create Date: 2026-09-09 13:38:07.960984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83f96ca208c6'
down_revision: Union[str, None] = 'e922b47ac98b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
