"""add filing_documents table and versioning

Revision ID: 83f96ca208c6
Revises: e922b47ac98b
Create Date: 2026-09-09 13:38:07.960984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83f96ca208c6'
down_revision: Union[str, None] = 'e922b47ac98b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('filing_documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('filing_id', sa.String(length=36), nullable=False),
    sa.Column('document_group_id', sa.String(length=36), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('document_name', sa.String(length=120), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('stored_filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_latest', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('uploaded_by_type', sa.String(length=20), nullable=False),
    sa.Column('uploaded_by_id', sa.String(length=36), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['filing_id'], ['tax_filings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_filing_documents_document_group_id'), 'filing_documents', ['document_group_id'], unique=False)
    op.create_index(op.f('ix_filing_documents_filing_id'), 'filing_documents', ['filing_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_filing_documents_filing_id'), table_name='filing_documents')
    op.drop_index(op.f('ix_filing_documents_document_group_id'), table_name='filing_documents')
    op.drop_table('filing_documents')
    # ### end Alembic commands ###
